title: 'Digital Artifact'
controls:
   up: 'W'
   down: 'S'
   left: 'A'
   right: 'D'
   about: 'F1'
terminal:
   height: 61
   width: 61
   font: 'Monospaced'
   fontSize: 12
   background: 'background00'
   foreground:
      - 'term00'
      - 'term01'
      - 'term02'
map:
   height: 200
   width: 200
update:
   download_url: 'https://github.com/chhensley/DigitalArtifact/releases/latest/download/digitalartifact.zip'
   jar: 'decompress.jar'
   cmd: 'java -jar DigitalArtifact.jar'
gui:
   sidebar_width: 600
   log_size: 40