title: 'Digital Artifact'
controls:
   up: 'W'
   down: 'S'
   left: 'A'
   right: 'D'
terminal:
   height: 80
   width: 80
   fontSize: 10
   background: 'background00'
map:
   height: 200
   width: 200
update:
   download_url: 'https://file-examples.com/wp-content/uploads/2017/02/zip_2MB.zip'
   jar: 'decompress.jar'
   cmd: 'java -jar DigitalArtifact.jar'